[package]
name = "octra-installer"
version = "1.0.0-local"
edition.workspace = true
description = "Octra App custom installer"
publish = false

[dependencies]
directories = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tauri = { workspace = true }
tauri-plugin-dialog = { workspace = true }
tauri-plugin-opener = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "fs"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
zip = { workspace = true, features = ["deflate"] }

[target."cfg(windows)".dependencies]
windows = { workspace = true, features = [
	"Win32_Foundation",
	"Win32_System_Com",
	"Win32_UI_Shell",
] }
winreg = { workspace = true }

[build-dependencies]
tauri-build = { workspace = true }

[lints]
workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(has_payload)"] }
